name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: rm -rf dist
    - run: npm run build
    - run: |
        EMAIL=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/users/$GITHUB_ACTOR | jq -r .email)
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$EMAIL"
    - run: git add dist
    - run: git commit -m "Build and commit dist"
    - run: git push origin $GITHUB_REF

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}