name: Build dist

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "dist"

    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      run: git rm -r dist

    - run: npm run build
    - run: git config --local user.name "$GITHUB_ACTOR"
    - run: git config --local user.email "${{ github.event.pusher.email }}"
    - run: git commit -a -m "Build and commit dist"
    - run: git push origin $GITHUB_REF
