name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: rm -rf dist
    - run: git rm -r dist
    - run: npm run build
    - run: git config --local user.name "$GITHUB_ACTOR"
    - run: git config --local user.email "${{ github.event.pusher.name }}"
    - run: git commit -a -m "Build and commit dist"
    - run: git push origin $GITHUB_REF

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}